steps:
# build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/low-brow-labs-com/hire-me:$SHORT_SHA', '.']
# push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/low-brow-labs-com/hire-me:$SHORT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'hire-me'
  - '--image'
  - 'gcr.io/low-brow-labs-com/hire-me:$SHORT_SHA'
  - '--region'
  - 'us-east1'
  - '--platform'
  - 'managed'
images:
- 'gcr.io/low-brow-labs-com/hire-me:$SHORT_SHA'




